name: Deploy to Preview Channel

on:
  push:
  pull_request:
jobs:

  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'yarn && yarn build'
        env:
          CI: ""
      # Add additional build steps here
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: run_firebase_preview
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GDSC_DJU }}'
          projectId: gdsc-dju
          expires: 14d
          channelId: preview
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
      - name: Commit Comment
        uses: peter-evans/commit-comment@v2.0.0
        with:
          body: | 
            ${{steps.run_firebase_preview.conclusion}}
            ${{steps.run_firebase_preview.status}}
            ${{job.status}}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
