name: Deploy to Live Channel

on:
  push:
    branches:
      - master
jobs:
  Deploy_Live_channel:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{ steps.run_firebase_deploy.outputs.details_url }}
    steps:
      - uses: actions/checkout@v2
      - run: 'yarn && yarn build'
        env:
          CI: ""
      # Add additional build steps here
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GDSC_DJU }}'
          channelId: live
          projectId: gdsc-dju
      - name: Commit Comment
        uses: peter-evans/commit-comment@v2.0.0
        with:
          body: |
            Deployed to Live channel.
            이벤트 명: ${{github.event_name}}
            작업자: ${{github.actor}}
            빌드여부: ${{steps.run_firebase_deploy.conclusion}}
            URL : ${{steps.run_firebase_deploy.outputs.details_url}}
            빌드 시간: ${{steps.run_firebase_deploy.outputs.expire_time}}
