name: Deploy to Preview Channel

on:
  push:
  pull_request:
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'yarn && yarn build'
        env:
          CI: ""
      # Add additional build steps here
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: run_firebase_preview
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GDSC_DJU }}'
          projectId: gdsc-dju
          expires: 14d
          channelId: preview
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
      - name: Commit Comment
        uses: peter-evans/commit-comment@v2.0.0
        with:
          body: |
            Deployed to preview channel.
            이벤트 명: ${{github.event_name}}
            작업자: ${{github.actor}}
            빌드여부: ${{steps.run_firebase_preview.conclusion}}
            프리뷰 링크: ${{steps.run_firebase_preview.outputs.details_url}}
            빌드 시간: ${{steps.run_firebase_preview.outputs.expire_time}}
