name: Deploy to Live Channel

on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'yarn && yarn build'
        env:
          CI: ""
      # Add additional build steps here
  Deploy_Live_channel:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: run_firebase_deploy
        run: './node_modules/.bin/firebase deploy --only hosting --project gdsc-dju --token ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GDSC_DJU }}'