name: Deploy to Live Channel

on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: 'yarn && yarn build'
        env:
          CI: ""
      # Add additional build steps here
  Deploy_Live_channel:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GDSC_DJU }}

      - name: Commit Comment
        uses: peter-evans/commit-comment@v2.0.0
        with:
          body: |
            Deployed to Live channel.
            이벤트 명: ${{github.event_name}}
            작업자: ${{github.actor}}
            빌드여부: ${{steps.run_firebase_deploy.conclusion}}
            URL : ${{steps.run_firebase_deploy.outputs.details_url}}
            빌드 시간: ${{steps.run_firebase_deploy.outputs.expire_time}}
